name: swit
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2023.01.10
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2022.12.7
  - colorama=0.4.4
  - configargparse=1.5.2
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.1
  - hdf5=1.10.6
  - icu=68.1
  - importlib_resources=5.2.2
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libiconv=1.16
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - ninja=1.10.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - pandas=1.3.1
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.3
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycairo=1.20.1
  - pyparsing=2.4.7
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.9.0
  - pytz=2021.1
  - rdkit=2021.03.4
  - readline=8.1
  - reportlab=3.5.68
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.12.2
  - setuptools=49.6.0
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - tbb=2021.3.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.62.0
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==21.2.0
    - blessings==1.7
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - click==8.0.1
    - colorful==0.5.4
    - dill==0.3.4
    - filelock==3.0.12
    - flatbuffers==1.12
    - fsspec==2021.7.0
    - future==0.18.2
    - gast==0.4.0
    - google-api-core==1.31.1
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.37.0
    - h5py==3.1.0
    - hiredis==2.0.0
    - idna==3.2
    - jsonschema==3.2.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - molvs==0.1.1
    - msgpack==1.0.2
    - multidict==5.1.0
    - multiprocess==0.70.12.2
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - opt-einsum==3.3.0
    - packaging==21.0
    - pathos==0.2.8
    - pox==0.3.0
    - ppft==1.6.6.4
    - prometheus-client==0.11.0
    - protobuf==3.17.3
    - psutil==5.8.0
    - py-spy==0.3.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pydeprecate==0.3.1
    - pyrsistent==0.18.0
    - pytorch-lightning==1.4.1
    - pyyaml==5.4.1
    - ray==1.5.1
    - redis==3.5.3
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.15.0
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow==2.6.0
    - termcolor==1.1.0
    - torchmetrics==0.4.1
    - typeguard==2.12.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - yarl==1.6.3
